/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'pendingCount' : bigint,
  'cancelledCount' : bigint,
  'totalBookings' : bigint,
  'completedCount' : bigint,
  'confirmedCount' : bigint,
  'totalRevenue' : bigint,
}
export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'userId' : Principal,
  'date' : string,
  'notes' : string,
  'serviceId' : bigint,
  'timeSlot' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'amount' : bigint,
  'appointmentId' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'durationMinutes' : bigint,
  'category' : ServiceCategory,
  'price' : bigint,
}
export type ServiceCategory = { 'bridal' : null } |
  { 'hair' : null } |
  { 'nails' : null } |
  { 'makeup' : null } |
  { 'facial' : null };
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'completePayment' : ActorMethod<[bigint], undefined>,
  'createAppointment' : ActorMethod<[bigint, string, string, string], bigint>,
  'createPayment' : ActorMethod<[bigint, bigint], bigint>,
  'createService' : ActorMethod<
    [string, ServiceCategory, bigint, bigint, string, string, boolean],
    bigint
  >,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAppointment' : ActorMethod<[bigint], [] | [Appointment]>,
  'getAvailableTimeSlots' : ActorMethod<[string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getPaymentByAppointment' : ActorMethod<[bigint], [] | [Payment]>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'listMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'saveCallerUserProfile' : ActorMethod<[string, string, string], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
  'updateService' : ActorMethod<
    [bigint, string, ServiceCategory, bigint, bigint, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];