/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'hair' : IDL.Null,
  'skin' : IDL.Null,
  'nails' : IDL.Null,
  'makeup' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'pendingCount' : IDL.Nat,
  'cancelledCount' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'confirmedCount' : IDL.Nat,
  'upcomingBookingsCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'todayBookingsCount' : IDL.Nat,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'serviceId' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'profilePictureUrl' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'amount' : IDL.Nat,
  'appointmentId' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'category' : ServiceCategory,
  'price' : IDL.Nat,
});
export const GalleryPhoto = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'uploadedAt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'completePayment' : IDL.Func([IDL.Nat], [], []),
  'createAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPayment' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createService' : IDL.Func(
      [
        IDL.Text,
        ServiceCategory,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteGalleryPhoto' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAdminStats' : IDL.Func([IDL.Text], [AdminStats], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
  'getAvailableTimeSlots' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getPaymentByAppointment' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Payment)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
  'listMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  'updateService' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        ServiceCategory,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'hair' : IDL.Null,
    'skin' : IDL.Null,
    'nails' : IDL.Null,
    'makeup' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'pendingCount' : IDL.Nat,
    'cancelledCount' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'confirmedCount' : IDL.Nat,
    'upcomingBookingsCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'todayBookingsCount' : IDL.Nat,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'serviceId' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'profilePictureUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'amount' : IDL.Nat,
    'appointmentId' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'category' : ServiceCategory,
    'price' : IDL.Nat,
  });
  const GalleryPhoto = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'uploadedAt' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'completePayment' : IDL.Func([IDL.Nat], [], []),
    'createAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPayment' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createService' : IDL.Func(
        [
          IDL.Text,
          ServiceCategory,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteGalleryPhoto' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAdminStats' : IDL.Func([IDL.Text], [AdminStats], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
    'getAvailableTimeSlots' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getPaymentByAppointment' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Payment)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listGalleryPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
    'listMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
    'updateService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          ServiceCategory,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };