/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GalleryPhoto {
    id: bigint;
    title: string;
    imageUrl: string;
    category: string;
    uploadedAt: string;
}
export interface AdminStats {
    pendingCount: bigint;
    cancelledCount: bigint;
    totalBookings: bigint;
    completedCount: bigint;
    confirmedCount: bigint;
    upcomingBookingsCount: bigint;
    totalRevenue: bigint;
    todayBookingsCount: bigint;
}
export interface Service {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: string;
    durationMinutes: bigint;
    category: ServiceCategory;
    price: bigint;
}
export interface Payment {
    id: bigint;
    status: PaymentStatus;
    amount: bigint;
    appointmentId: bigint;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    userId: Principal;
    date: string;
    notes: string;
    serviceId: bigint;
    timeSlot: string;
}
export interface UserProfile {
    id: Principal;
    name: string;
    role: UserRole;
    email: string;
    profilePictureUrl: string;
    phone: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum ServiceCategory {
    hair = "hair",
    skin = "skin",
    nails = "nails",
    makeup = "makeup"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGalleryPhoto(title: string, category: string, imageUrl: string, uploadedAt: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    completePayment(paymentId: bigint): Promise<void>;
    createAppointment(serviceId: bigint, date: string, timeSlot: string, notes: string): Promise<bigint>;
    createPayment(appointmentId: bigint, amount: bigint): Promise<bigint>;
    createService(name: string, category: ServiceCategory, price: bigint, durationMinutes: bigint, description: string, imageUrl: string, isActive: boolean): Promise<bigint>;
    deleteGalleryPhoto(photoId: bigint): Promise<void>;
    deleteService(serviceId: bigint): Promise<void>;
    getAdminStats(todayDate: string): Promise<AdminStats>;
    getAppointment(appointmentId: bigint): Promise<Appointment | null>;
    getAvailableTimeSlots(date: string): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getPayment(paymentId: bigint): Promise<Payment | null>;
    getPaymentByAppointment(appointmentId: bigint): Promise<Payment | null>;
    getService(serviceId: bigint): Promise<Service | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllAppointments(): Promise<Array<Appointment>>;
    listAllUserProfiles(): Promise<Array<UserProfile>>;
    listGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    listMyAppointments(): Promise<Array<Appointment>>;
    listServices(): Promise<Array<Service>>;
    saveCallerUserProfile(name: string, phone: string, email: string, profilePictureUrl: string): Promise<void>;
    updateAppointmentStatus(appointmentId: bigint, status: AppointmentStatus): Promise<void>;
    updateService(serviceId: bigint, name: string, category: ServiceCategory, price: bigint, durationMinutes: bigint, description: string, imageUrl: string, isActive: boolean): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, Payment as _Payment, PaymentStatus as _PaymentStatus, Service as _Service, ServiceCategory as _ServiceCategory, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGalleryPhoto(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPhoto(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPhoto(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePayment(arg0);
            return result;
        }
    }
    async createAppointment(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createPayment(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1);
            return result;
        }
    }
    async createService(arg0: string, arg1: ServiceCategory, arg2: bigint, arg3: bigint, arg4: string, arg5: string, arg6: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteGalleryPhoto(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryPhoto(arg0);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAdminStats(arg0: string): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats(arg0);
            return result;
        }
    }
    async getAppointment(arg0: bigint): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTimeSlots(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentByAppointment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentByAppointment(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentByAppointment(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAppointments();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAppointments();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUserProfiles();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUserProfiles();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryPhotos();
            return result;
        }
    }
    async listMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAppointments();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAppointments();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: AppointmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: string, arg2: ServiceCategory, arg3: bigint, arg4: bigint, arg5: string, arg6: string, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, to_candid_ServiceCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _UserRole;
    email: string;
    profilePictureUrl: string;
    phone: string;
}): {
    id: Principal;
    name: string;
    role: UserRole;
    email: string;
    profilePictureUrl: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n13(_uploadFile, _downloadFile, value.role),
        email: value.email,
        profilePictureUrl: value.profilePictureUrl,
        phone: value.phone
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    amount: bigint;
    appointmentId: bigint;
}): {
    id: bigint;
    status: PaymentStatus;
    amount: bigint;
    appointmentId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n20(_uploadFile, _downloadFile, value.status),
        amount: value.amount,
        appointmentId: value.appointmentId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: string;
    durationMinutes: bigint;
    category: _ServiceCategory;
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: string;
    durationMinutes: bigint;
    category: ServiceCategory;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        imageUrl: value.imageUrl,
        durationMinutes: value.durationMinutes,
        category: from_candid_ServiceCategory_n25(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    userId: Principal;
    date: string;
    notes: string;
    serviceId: bigint;
    timeSlot: string;
}): {
    id: bigint;
    status: AppointmentStatus;
    userId: Principal;
    date: string;
    notes: string;
    serviceId: bigint;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n8(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        notes: value.notes,
        serviceId: value.serviceId,
        timeSlot: value.timeSlot
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hair: null;
} | {
    skin: null;
} | {
    nails: null;
} | {
    makeup: null;
}): ServiceCategory {
    return "hair" in value ? ServiceCategory.hair : "skin" in value ? ServiceCategory.skin : "nails" in value ? ServiceCategory.nails : "makeup" in value ? ServiceCategory.makeup : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n23(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    hair: null;
} | {
    skin: null;
} | {
    nails: null;
} | {
    makeup: null;
} {
    return value == ServiceCategory.hair ? {
        hair: null
    } : value == ServiceCategory.skin ? {
        skin: null
    } : value == ServiceCategory.nails ? {
        nails: null
    } : value == ServiceCategory.makeup ? {
        makeup: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
